# Generated by Django 5.0.4 on 2024-04-29 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'doctor'), ('patient', 'patient')], max_length=10)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('picture', models.ImageField(default='user.jpg', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact', models.PositiveIntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('speciality', models.CharField(choices=[('Cardiologist', 'Cardiologist'), ('Nephrologiest', 'Nephrologiest'), ('Pulmonologist', 'Pulmonologist'), ('Ophthalmologist', 'Ophthalmologist'), ('Neurologist', 'Neurologist'), ('Rheumatologist', 'Rheumatologist'), ('Dermatologist', 'Dermatologist'), ('Hematologist', 'Hematologist'), ('Somnologist', 'Somnologist')], max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('Hospital_Affiliations', models.TextField()),
                ('Medical_School', models.TextField()),
                ('Experience', models.TextField()),
                ('Internship', models.TextField()),
                ('country', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('contact', models.PositiveIntegerField()),
                ('certificate', models.ImageField(null=True, upload_to='doc/')),
                ('about', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=20)),
                ('service', models.CharField(choices=[('heart Problem', 'heart Problem'), ('Diagnostic Testing', 'Diagnostic Testing'), ('kidneys Problem', 'kidneys Problem'), ('Treatment of Acute Kidney Injury', 'Treatment of Acute Kidney Injury'), ('Lung Problem', 'Lung Problem'), ('Sleep Medicine Services', 'Sleep Medicine Services'), ('Respiratory Disease Diagnosis', 'Respiratory Disease Diagnosis'), ('Retina and Vitreous Services', 'Retina and Vitreous Services'), ('Eye Problem', 'Eye Problem'), ('Cornea and External Disease Services', 'Cornea and External Disease Services'), ('Epilepsy Management and Seizure Disorders', 'Epilepsy Management and Seizure Disorders'), ('Stroke Care and Management', 'Stroke Care and Management'), ('brain Problem', 'brain Problem'), ('Management of Autoimmune Diseases', 'Management of Autoimmune Diseases'), ('Management of Musculoskeletal Conditions', 'Management of Musculoskeletal Conditions'), ('Diagnosis and Treatment of Skin Conditions', 'Diagnosis and Treatment of Skin Conditions'), ('Cosmetic Dermatology Services', 'Cosmetic Dermatology Services'), ('Management of Blood Disorders', 'Management of Blood Disorders'), ('Management of Hematologic Malignancies', 'Management of Hematologic Malignancies'), ('Diagnosis and Management of Sleep Disorders', 'Diagnosis and Management of Sleep Disorders'), ('Treatment and Management of Sleep Disorders', 'Treatment and Management of Sleep Disorders')], max_length=50)),
                ('appointment_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('info', models.TextField()),
                ('doctor_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor_info')),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
