# Generated by Django 5.0.4 on 2024-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_appointment_appointment_status_pandding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_info',
            name='country',
            field=models.CharField(choices=[('America', 'America'), ('Australia', 'Australia'), ('Canada', 'Canada'), ('India', 'India'), ('UK', 'UK'), ('Other', 'Other')], max_length=20),
        ),
    ]
